### PR TITLE
WIP on PyLong support

### PR DESCRIPTION
**Pull request by swenson**
Tracked in https://github.com/pybee/batavia/issues/223

* Adedd vendored code to build and clean up so that it runs
* Vendored bignumber JS library
* Starting working on PyLong marshal function and integrating PyLongs.

I don't even like this library, but I want to get *something* in. All of the JS bignumber libraries appear to be flawed in some ways.

Still a lot to do, but I wanted to check in.

### CODE REVIEW

**Comment by glasnt** [comment]
@swenson I've marked this one as a Work In Progress. Once you have something you're happy with that CI agrees is good, ping this PR and I'll get it merged 👍

**Comment by swenson** [comment]
Thanks! Should be a lot of fun.

**Comment by swenson** [comment]
Tests pass! I updated #223 to track further progress on this issue, but this should be in a good position to merge. :)

**Comment by glasnt** [comment]
woop woop!

**Comment by swenson** [comment]
Thanks!

**Pull request merged**
