### PR TITLE
Create default error for dict binary less than, less than or equal and power operator

### PR DESCRIPTION
**Pull request by xpostudio4**

### CODE REVIEW

**Comment by xpostudio4** [comment]
I'm not sure the error above makes sense

**Comment by glasnt** [comment]
@xpostudio4 I've kicked off another build for you.

You are also going to have to rebase your changes for this pull request to be merged 

https://help.github.com/articles/about-git-rebase/

**Comment by xpostudio4** [comment]
@glasnt do you have any idea why the build does not finish?, all the test run well on my machine (I hate to say that).

**Comment by glasnt** [comment]
@xpostudio4  I'm not quite sure. At one point I wasn't sure if we were being rate limited by Travis. I'll have to investigate this further to be sure.

**Comment by freakboy3742** [comment]
Unfortunately, due to the confusion during the sprints, the `__le__` and `__lt__` operators were merged from another contributor; however, the `__pow__` implementation was new, so I've just merged that one. Thanks for the contribution, and apologies for the time wasted!

**Pull request merged**
