### PR TITLE
[WIP] Added in simple test for comparing tuples and enabled unit tests

### PR DESCRIPTION
**Pull request by slick666**

### CODE REVIEW

**Comment by glasnt** [comment]
I've marked this as "Work in Progress". At the moment Travis is reporting errors, so those need to be addressed as well.

Once you're happy with this PR, let us know :)

**Comment by slick666** [comment]
thanks @glasnt hoping to knock it out this weekend.

**Comment by phildini** [comment]
Hi there! Is this PR still being actively worked on? It's gone stale against master, and hasn't been touched for over a year. 

We'll be closing this on September 17th, 2017 to keep the queue clear if we don't hear anything, and in any case thanks for your time!

**Comment by phildini** [comment]
Hi there! We're closing this at this point, but feel free to re-open if you're interested in continuing it!

**Pull request closed without merging**
