### PR TITLE
Add Set iand functionality

### PR DESCRIPTION
**Pull request by havocbane**
I have updated the Set.js implementation so that iand (&=) operations work for base types. I also removed the .DS_Store files that got added to the project mistakenly and updated the ignore rules so they don't sneak back in.

### CODE REVIEW

**Comment by phildini** [comment]
This looks great! I'll try to poke at travis and see what's going on with tests.

**Comment by havocbane** [comment]
Thanks! I was wondering that myself since I didn't see it in the build queue.

**Comment by jcronyn** [comment]
Sweeeeet 👍

**Comment by freakboy3742** [comment]
I have no idea why Travis didn't pick this up.

I downloaded the patch and reviewed it locally; it looks great, but there are 4 unexpected successes in the builtins. By correcting the constructor for `set`, you've inadvertently corrected the set tests for the `print`, `repr`, `set` and `str` builtins. So, delete those four tests from the not_implemented lists for builtins, resubmit, and you should be good to merge (and hopefully, Travis will like you this time!)

**Comment by freakboy3742** [comment]
It also appears that you've fixed the >, >=, < and <= binary operators for set (at least, they pass unexpectedly on my machine).

**Comment by havocbane** [comment]
Thank you for the feedback. I will address those issues as soon as I can.

**Comment by freakboy3742** [comment]
Thanks for the contribution!

**Pull request merged**
