### PR TITLE
implemented __mul__ for set

### PR DESCRIPTION
**Pull request by sethMittag**

### CODE REVIEW

**Comment by sethMittag** [comment]
Im not sure what this error means.

**Comment by sethMittag** [comment]
I think travis hates me.

**Comment by glasnt** [comment]
Travis doesn't like anyone right now. 

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

There are Plans™ to make Travis behave, but for now, I'll kick your build off again, see if it's feeling happier this time.

**Comment by sethMittag** [comment]
Thanks @freakboy3742

**Pull request merged**
