### PR TITLE
Fix #427 - Add and enforce linting rules

### LINKED ISSUE #427: Enforce code style for JavaScript files
I was looking at the code in `batavia/types/Tuple.js` and noticed there's a mix of tabs and spaces in that file. I went looking for a code style guide for the JavaScript files and didn't notice one (I may not have looked hard enough though).

I usually use `.editorconfig` files to dictate my indentation style for various types of files because my text editor always seems to disagree with the authors of the projects I contribute to by default.

I propose two things:
1. that batavia adopt an [EditorConfig][] file
2. that some semi-automated sed magic (or similar) be used to make the mixed indentation more consistent

Thoughts on those two suggestions?

⚠️ **Disclaimer** I'm one of the people who created EditorConfig. It is used by some pretty popular projects already though (e.g. Django, Drupal, Wordpress, Node, Angular, jQuery).

[editorconfig]: http://editorconfig.org/

### PR DESCRIPTION
**Pull request by freakboy3742**

### CODE REVIEW

**Comment by freakboy3742** [comment]
@treyhunner I've just added a first cut at an .editorconfig file; would be interested in your feedback.

**Comment by treyhunner** [comment]
That `.editorconfig` file looks good to me!

**Comment by glasnt** [comment]
The python tests are now successful!

But eslint has some itty bitty errors.

**Comment by freakboy3742** [comment]
I'm not seeing any lint errors - are you working off c0e6370?

**Comment by glasnt** [comment]
... I may have been looking at the wrong commit. 

Looks fine now!

Is this ready to merge?

**Comment by freakboy3742** [comment]
I believe so - no lint problems, and no CI errors... if you like what you see, :shipit:

**Pull request merged**
