### PR TITLE
Set⭕

### PR DESCRIPTION
**Pull request by rixx**

### CODE REVIEW

**Comment by rixx** [comment]
This should provide a complete implementation of operations on `set` according to tests (reducing expected failures by about 350).

Originally, these were 23 commits. I reduced them to 13 by squashing them where appropriate - not sure if you want me to squash them further? I like commits not to get too large, to still be understandable and readable, but I can squash them further if you'd prefer that.

**Comment by glasnt** [comment]
I don't believe we're fussed on the squashing at this point. If we have any preferred process in the future, we'll document it.

**Comment by rixx** [comment]
There might be test failures due to unexpected successes (had those with `frozenset`) - if so, I'll fix them in about six hours, when it's morning and stuff.

**Comment by glasnt** [comment]
These are the results (first build timed out), 17 unexpected successed

```
test_set_None (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_NotImplemented (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_bool (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_bytearray (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_bytes (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_class (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_complex (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_dict (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_float (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_frozenset (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_int (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_list (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_range (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_set (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_slice (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_str (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
test_set_tuple (tests.builtins.test_pow.BuiltinTwoargPowFunctionTests) ... unexpected success
```

**Pull request merged**
