### PR TITLE
Fixes for Batavia

### PR DESCRIPTION
**Pull request by freakboy3742**
Includes changes to webpack packaging, and the introduction of a session-based mode for the VirtualMachine.

### CODE REVIEW

**Comment by glasnt** [comment]
The tests for this are failing badly.

**Comment by freakboy3742** [comment]
The tests are now passing well... :-)

**Comment by glasnt** [comment]
With these changes, is the testbed still ok?

**Comment by freakboy3742** [comment]
Yes - it's still good. Better even, because stack traces now report the right file.

**Pull request merged**
