### PR TITLE
Several List operator functions implemented

### PR DESCRIPTION
**Pull request by asherScott**
Implemented the following List operator functions:
```
List.prototype.__pow__
List.prototype.__div__
List.prototype.__mod__
List.prototype.__lshift__
List.prototype.__rshift__
List.prototype.__and__
List.prototype.__xor__
List.prototype.__or__
List.prototype.__and__
List.prototype.__floordiv__
List.prototype.__truediv__
List.prototype.__iadd__
List.prototype.__isub__
List.prototype.__imul__
List.prototype.__imod__
List.prototype.__ipow__
List.prototype.__irshift__
List.prototype.__ilshift__
List.prototype.__iand__
List.prototype.__ixor__
List.prototype.__ior__
```

*Note:*
~~For some reason the `test_multiply_int` and `test_multiply_bool` under the `BinaryListOperationTests` are failing.  I am wondering if the tests are buggy or if there are some special cases that are not being caught in the current implementation of `List.prototype.__mul__`.  I attempted to catch any additional cases, however the test failures remain.  I replaced them in their respective unimplemented list for the time being.~~
`test_multiply_int` and `test_multiply_bool` seem to work fine on travis-ci, maybe the tests are just goofy on my local machine.

### CODE REVIEW

**Comment by freakboy3742** [comment]
Fantastic! Thanks for the contribution!

**Comment by freakboy3742** [comment]
I'd be interested to see what errors you were getting for `test_multiply_int` and `test_multiply_bool` - my immediate guess would be that it's just an formatting inconsistency, but if it's something more than that, it would be interesting to see what the problem is so was can make sure nobody else is affected.

**Comment by asherScott** [comment]
@freakboy3742 
Here is the failure output when running the list tests:
`
======================================================================
FAIL: test_multiply_bool (tests.datatypes.test_list.BinaryListOperationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asher/Projects/batavia/tests/utils.py", line 815, in func
    substitutions=SAMPLE_SUBSTITUTIONS
  File "/home/asher/Projects/batavia/tests/utils.py", line 858, in assertBinaryOperation
    substitutions=substitutions
  File "/home/asher/Projects/batavia/tests/utils.py", line 485, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: 'Confused END_FINALLY\n' != "[]\n[]\n[3, 4, 5]\n[]\n[1, 2, 3, 4, 5, 6[37 chars][]\n"
- Confused END_FINALLY
+ []
+ []
+ [3, 4, 5]
+ []
+ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
+ []
+ ['a', 'b', 'c']
+ []
 : Global context: Error running x * y

======================================================================
FAIL: test_multiply_int (tests.datatypes.test_list.BinaryListOperationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asher/Projects/batavia/tests/utils.py", line 815, in func
    substitutions=SAMPLE_SUBSTITUTIONS
  File "/home/asher/Projects/batavia/tests/utils.py", line 858, in assertBinaryOperation
    substitutions=substitutions
  File "/home/asher/Projects/batavia/tests/utils.py", line 485, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '[]\n[]\n[]\nConfused END_FINALLY\n' != "[]\n[]\n[]\n[3, 4, 5, 3, 4, 5, 3, 4, 5]\[163 chars][]\n"
  []
  []
  []
- Confused END_FINALLY
+ [3, 4, 5, 3, 4, 5, 3, 4, 5]
+ []
+ []
+ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
+ []
+ []
+ ['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c']
+ []
+ []
 : Global context: Error running x * y
`

**Comment by asherScott** [comment]
Hopefully that is readable.  Not sure the best way to format error outputs here.

**Pull request merged**
