### PR TITLE
Implement subscription for range()

### PR DESCRIPTION
**Pull request by Slepice1**
Single number indexing is working with long.

### CODE REVIEW

**Comment by glasnt** [comment]
Hi @Slepice1 

This PR is timing out on CI, specifically on the test which this PR implements, so there may be a bug in your code. We've also recently pushed a whole lot of base functionality changes, so this PR needs to be rebased.

**Comment by Slepice1** [comment]
I rebased and fixed the issue, it should pass all the tests now.

**Comment by glasnt** [comment]
For some reason, CI never picked up these changes. Possibly due to the merge commit. 

I'm running these tests over in https://circleci.com/gh/pybee/batavia/450

**Comment by glasnt** [comment]
@Slepice1 there's a bunch of errors messages that might help on the build I linked above. 
We don't mind a verbose commit history, it seems that complex rebasing and CircleCI might not mix.

**Comment by Slepice1** [comment]
Okay it *should* be fixed now, I forgot to test with Python3.4. Please run the tests again.

**Comment by glasnt** [comment]
Yup, https://circleci.com/gh/pybee/batavia/452 is green!

**Pull request merged**
