### PR TITLE
Parse args with click

### PR DESCRIPTION
**Pull request by tonnydourado**
This implements the argument parsing logic with click. refs #275

### CODE REVIEW

**Comment by tonnydourado** [comment]
The main advantage of click is that it allows you to express the validations for the command line arguments in a declarative way, which tends to be shorter and easier to read. With argparse all the checks like 'is this a valid path?', 'does this path exists?', 'is it a directory', have to be manually coded. On click, it's just a parameter in a decorator.

It also supports sub commands, which allows you to build pretty complex CLIs with just a bunch of functions and some decorators.

That said, this script has just two parameters as it is, so, might not be worth yet. But as more of the ideas from #275 are implemented, the advantages might become more worth adding the dependency. 

On the other hand, I tried to implement that idea of having the arguments come from a config file and it didn't play out as smoothly with click as I hoped, so, there's that too.

**Comment by freakboy3742** [comment]
@tonnydourado Thanks for that clarification.

@glasnt @swenson @phildini Do you have any thoughts on this?

**Comment by swenson** [comment]
I quite like `click`'s style. However, I do agree that it seems premature to use it, as we don't have a complex CLI or enough options to justify the extra dependency.

**Comment by glasnt** [comment]
Thank you for your time and explanation, @tonnydourado. Based on the comments above, I'm going to close out this PR. 

If we end up with a more complex CLI, we can revisit this.

**Pull request closed without merging**
