### PR TITLE
Fixed some broken links in 'docs/how-to' section

### PR DESCRIPTION
**Pull request by pranavmodx**
- Updated the links given in the documentation to the correct destinations.
- The links are directed to the desired pages and 'page not found' errors are eliminated.
- Refs #828 

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
I'm not sure how you tested these, but I'm not seeing any change when I try these modifications locally. Sphinx doesn't require referencing the `.rst` extension in it's links...

**Comment by pranavmodx** [comment]
I tested them from the preview feature of GitHub itself. It seems to be working fine.

What I've observed is that the links before my changes were of the format - <main_url>/docs/how-to/<file_name_without_extension> and these didn't work

After inserting the extension in the links to get the format - <main_url>/docs/how-to/<file_name_with_extension> , they worked perfectly fine. 
When the reference '.rst' is added in the links, they redirect to links of this working format.

Also, only 1 link has the wrong path (Tutorial 0). The other two have the right paths but the extension referencing is not there.

**Comment by freakboy3742** [comment]
Github doesn't do a very good job of rendering ReStructured Text, and doesn't render Sphinx directives at all. Github's rendering isn't a useful reference in this case.

To verify the rendering, you need to use Sphinx to build the documentation, like it says in the [docs contribution guide](https://batavia.readthedocs.io/en/latest/how-to/contribute-docs.html).

**Comment by phildini** [comment]
Hi there! It looks like this PR might be dead, so we're closing it for now. Feel free to re-open it if you'd like to continue, or think about directing your efforts to https://github.com/beeware/briefcase or https://github.com/beeware/toga. Both of these have more active development right now. 😄

**Pull request closed without merging**
