### PR TITLE
Experimental support for generators.

### PR DESCRIPTION
**Pull request by rfk**
Hi @freakboy3742 - I managed to get the two existing generator test-cases passing without too much drama, would love to get your feedback on the approach I'm taking here before I go too much further with it.

Also, I hit a couple of yaks that needed shaving around `list()`, the hair's included as a separate commit.

### CODE REVIEW

**Comment by glasnt** [comment]
Hi! There's one itty bitty issue with this one

```
FAIL: test_str (tests.builtins.test_iter.BuiltinIterFunctionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pybee/batavia/tests/utils.py", line 995, in func
    substitutions=SAMPLE_SUBSTITUTIONS
  File "/home/travis/build/pybee/batavia/tests/utils.py", line 1041, in assertBuiltinFunction
    substitutions=substitutions
  File "/home/travis/build/pybee/batavia/tests/utils.py", line 494, in assertCodeExecution
    self.assertEqual(js_out, py_out, context)
AssertionError: '>>> [28 chars]x)\n<class \'TypeError\'> : \'str\' object is [474 chars]\n\n' != '>>> [28 chars]x)\n<str_iterator object at 0xXXXXXXXX>\n\n>>>[455 chars]\n\n'
  >>> f = iter
  >>> x = ""
  >>> f(x)
- <class 'TypeError'> : 'str' object is not iterable
+ <str_iterator object at 0xXXXXXXXX>
```

**Comment by rfk** [comment]
Thanks @glasnt!  TBH I'm surprised travis only showed one failure :-)

I'll dive into this some more today.

**Comment by rfk** [comment]
Since I'm still mucking around with the generators part of this, I'm going to pull the `list()` fixes out into a separate PR.

**Comment by glasnt** [comment]
So Travis is green on this, but Circle CI isn't. 

Because of issues with us using Travis CI too hard, I disabled Travis for Batavia and moved to Circle CI. 

@rfk If you rebase from master to get the `circle.yml` file in your branch, then push, it should trigger a Circle CI build and confirm the new tests are passing. 

Once you've done that and confirmed the change in scope of this PR (with a rename, if you could), then just ping me and I'll get this in.

**Comment by freakboy3742** [comment]
Travis and CircleCI are running the same tests, so the fact that we have a green board for Travis is enough to convince me that this is good to merge..

**Pull request merged**
