### PR TITLE
Additional frozenset operation

### PR DESCRIPTION
**Pull request by rixx**
xor, substraction, or, subscription

### CODE REVIEW

**Comment by glasnt** [comment]
Hey @rixx, let us know if you have any more additions to this one, and then we'll merge it for you ✨

**Comment by rixx** [comment]
Nope, `frozenset` is as done as it will be on normal operators. It's down to three expected test failures, that's the unary operators.

I'm going to do `set` next, but I'll have to decide on an emoji … [this](http://emojipedia.org/radio-button/) could look like a set with a subset?

**Comment by glasnt** [comment]
I'd use 🍱 [(bento)](http://emojipedia.org/bento-box/), as it's a set meal 😄

**Comment by glasnt** [comment]
Thanks for your continually amazing work on this, @rixx! ✨

**Comment by rixx** [comment]
Hah, I was thinking about something music related for DJ sets … :smile:

**Pull request merged**
