### PR TITLE
Implement license, help

### PR DESCRIPTION
**Pull request by glasnt**
Basic word stuff, proxying functionality because I really don't want to have to re-create a interactive help prompt in the console if that's ok 🙃

### CODE REVIEW

**Comment by swenson** [comment]
Am I allowed to review this? (If so, looks good to me! If not, it still does :) )

**Comment by glasnt** [comment]
🎉 

I just forced an empty push for the robot overloads, but once they are happy I'll :shipit:

**Comment by swenson** [comment]
All hail the robot overlords. :shipit:

**Comment by glasnt** [comment]
🤖 🆗

**Pull request merged**
