### PR TITLE
implemented __truediv__ for set

### PR DESCRIPTION
**Pull request by sethMittag**

### CODE REVIEW

**Comment by sethMittag** [comment]
Should I stop making pull request until Travis isn't mad at me? I don't want to be a nuisance but Im  having a great time and really like this project!!

**Comment by sethMittag** [comment]
Should I stop making pull request until Travis isn't mad at me? I don't want to be a nuisance but Im having a great time and really like this project!!

**Comment by glasnt** [comment]
Don't be sorry, @sethMittag! 

One of the two Travis builds were OK, the other one timed out. Since this is such a small change, I've merged it anyway :)

**Comment by freakboy3742** [comment]
@sethMittag What @glasnt said :-) Travis is being a bit precious at the moment; I think it's due to the memory requirements for running the full test suite. It's definitely not due to anything you've done. 

I've got an idea how we might be able to make the test suite run a whole lot faster, and hopefully address this failed build problem. In the meantime; keep on trucking as normal. If you can run the full test suite on your local machine and it passes, drop a note on the pull request. If the change looks straight forward enough and we can't get Travis to play ball after kicking it a couple of times, we'll probably just take your word for it and merge.

**Pull request merged**
