### PR TITLE
Edited README format and text and added CoC link

### PR DESCRIPTION
**Pull request by willingc**
@freakboy3742 I made some changes to the README on the plane yesterday. Let me know if you want any additional changes. Making a bigger commit than at PyCon ;-)

Changes:
- Reordered some content for better flow
- Added a link under community to CoC
- Updated formatting re: fetch/rebase under contributing
- Split part of "Why Batavia?" into more bite size chunks and bolded one sentence

### CODE REVIEW

**Comment by glasnt** [comment]
This is awesome, thanks Carol! 🎉 

I know there's a big documentation update coming RealSoonNow(tm), but this is a great change for now. 

I won't merge this myself, and leave that to @freakboy3742 

Aside: did you get your shiny coin for your contribution at PyCon US?

**Comment by willingc** [comment]
@glasnt Thanks for the nice feedback. I did get a shiny coin as a treasure for teaching git to some contributors. I told @freakboy3742 that I would send some "code" contributions too ;-)

**Comment by freakboy3742** [comment]
@willingc Thanks! As @glasnt said, there's change a-comin; but the perfect being the enemy of the good, I'll merge this and try to integrate some of these changes into the reworked home pages.

Plus, it formally validates the coin I gave you :-)

**Comment by willingc** [comment]
@freakboy3742 :D No worries about integrating stuff. Looking forward to the reworked home pages. The PR was a good excuse to play around with stuff. ⛵ ☕

**Pull request merged**
