### PR TITLE
Implemented Bool.__mod__(bool) part of issue #46

### PR DESCRIPTION
**Pull request by memo330179**

### CODE REVIEW

**Comment by jstoebel** [comment]
this being his first contribution can @memo330179 get a challenge coin for his efforts? Or does that have to be at a live sprint?

**Comment by freakboy3742** [comment]
@jstoebel This definitely *earns* a coin: unfortunately, we can't post them out individually - the postage costs would be too much - so I deliver them in person. 

@memo330179 Where are you based?

**Comment by jstoebel** [comment]
@freakboy3742 sounds like we need a CDN (coin delivery network)

**Comment by freakboy3742** [comment]
@jstoebel Well yes... if only to avoid the inevitable Distributed Denial of Coin attacks on the project... :-)

**Comment by jstoebel** [comment]
can I have a coin?
_no_
can I have a coin?
_no_
can I have a coin?
_no_
can I have a coin?
_nonononononononono_

**Pull request merged**
