### PR TITLE
Added some new functions and fixed the old ones

### PR DESCRIPTION
**Pull request by martini97**
Signed-off-by: martini97 alessandrofmartini@gmail.com

### CODE REVIEW

**Comment by phildini** [comment]
Hi there. Thanks for the PR! At first glance, I can't really tell why this version is improved over the old version. If you could add some tests that now pass with this version (that preferably wouldn't have passed with the old version) that would be great!

At the very least, an explanatory comment or two feel necessary.

**Comment by martini97** [comment]
The previous version didn't have the altchars for b64encode and b64decode, no validate for b64decode, and the urlsafe encode and decode wasn't replacing the + and /. I will insert the needed tests.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
I must be missing something; I can see the extra `altchars` argument, but the extra test cases you provide all pass without making any changes to the base64 methods (at least, they do in my testing)

I'm not denying that the changes are needed; but the tests you provide need to protect against regressions by demonstrating failing behavior before you make them pass.

**Comment by martini97** [comment]
@freakboy3742 I'm trying to add the tests, but there is some ASCII problem with the ascii, I've tried running it in python and it works so I'm a little lost,if you would like to see the errors they are here: http://pastebin.com/WtcdE11F

**Comment by phildini** [comment]
Hey there! So sorry we didn't see this sooner. If you're still interested in moving forward with this PR, would you mind rebasing and fixing the conflicts?

**Comment by shaib** [comment]
I've squashed and fixed the tests into one commit, based on current master, at https://github.com/shaib/batavia/tree/martini97-b64. The addition causes one test to fail.

The current implementation of b64encode and b64decode is completely different than what it was at the time this PR was written; they now rely on the base64-js library, which has no room for `altchars`. So a design decision needs to be made, if a written-from-scratch implementation is wanted. It seems one is required for 100% compatibility with CPython. If we do, we should probably completely replace the current implementation with something like we see here. We would also need to add tests for `altchars` on `b64decode()`.

**Comment by phildini** [comment]
Hi there! It looks like this PR might be dead, so we're closing it for now. Feel free to re-open it if you'd like to continue, or think about directing your efforts to https://github.com/beeware/briefcase or https://github.com/beeware/toga. Both of these have more active development right now. 😄

**Pull request closed without merging**
